function tests = test_Mobi_reference_population_metrics
    tests = functiontests(localfunctions);
end


function setupOnce(testCase)
    addpath(fileparts(fileparts(mfilename('fullpath'))));
end


function testReferencePopulationMetricsBasicCase(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "HLA-A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop1"], ...
        ["A"; "A"], ...
        ["A*01:01"; "A*02:01"], ...
        [0.20; 0.80], ...
        [36; NaN], ...
        [100; 100], ...
        'VariableNames', { ...
            'Population', ...
            'Locus', ...
            'Allele', ...
            'AlleleFrequency', ...
            'IndividualsFrequency', ...
            'SampleSize'});

    metrics = Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);

    verifyTrue(testCase, metrics.didEvaluate);
    verifyEqual(testCase, metrics.numSelectedPeptides, 1);
    verifyEqual(testCase, metrics.numHitHLAs, 1);
    verifyEqual(testCase, metrics.numReferencePopulations, 1);
    verifyEqual(testCase, metrics.coveragePercent, 36, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.expectedHits, 0.36, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.conditionalMeanHits, 1, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.pc90, 0, 'AbsTol', 1e-10);
end


function testReferencePopulationMetricsInfersAlleleFrequency(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        "Pop1", ...
        "A", ...
        "A*01:01", ...
        NaN, ...
        36, ...
        100, ...
        'VariableNames', { ...
            'Population', ...
            'Locus', ...
            'Allele', ...
            'AlleleFrequency', ...
            'IndividualsFrequency', ...
            'SampleSize'});

    metrics = Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);

    verifyTrue(testCase, metrics.didEvaluate);
    verifyEqual(testCase, metrics.coveragePercent, 36, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.expectedHits, 0.36, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.conditionalMeanHits, 1, 'AbsTol', 1e-10);
end


function testTwoLocusConvolutionCase(testCase)
    selectedPeptides = ["PEP1"; "PEP2"];

    combinedTable = table( ...
        ["PEP1"; "PEP2"], ...
        ["A*01:01"; "B*07:02"], ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop1"], ...
        ["A"; "B"], ...
        ["A*01:01"; "B*07:02"], ...
        [0.5; 0.5], ...
        [NaN; NaN], ...
        [100; 100], ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    metrics = Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);

    verifyEqual(testCase, metrics.coveragePercent, 93.75, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.expectedHits, 1.5, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.conditionalMeanHits, 1.6, 'AbsTol', 1e-10);
end


function testNonzeroPC90Case(testCase)
    selectedPeptides = ["PEP1"; "PEP2"];

    combinedTable = table( ...
        ["PEP1"; "PEP2"], ...
        ["A*01:01"; "A*02:01"], ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop1"], ...
        ["A"; "A"], ...
        ["A*01:01"; "A*02:01"], ...
        [0.5; 0.5], ...
        [NaN; NaN], ...
        [100; 100], ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    metrics = Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);

    verifyEqual(testCase, metrics.pc90, 1, 'AbsTol', 1e-10);
end


function testWeightedMixtureBehavior(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop2"], ...
        ["A"; "A"], ...
        ["A*01:01"; "A*01:01"], ...
        [0.5; 0.1], ...
        [NaN; NaN], ...
        [100; 300], ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    metrics = Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);

    expectedCoverage = 100 * (0.25 * 0.75 + 0.75 * 0.19);
    verifyEqual(testCase, metrics.coveragePercent, expectedCoverage, 'AbsTol', 1e-10);
    verifyEqual(testCase, sum(metrics.weightedMixturePMF), 1, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.populationWeightMode, "sample_size");
end


function testHitCountModeMultiplicityVsBinary(testCase)
    selectedPeptides = ["PEP1"; "PEP2"];

    combinedTable = table( ...
        ["PEP1"; "PEP2"], ...
        ["A*01:01"; "A*01:01"], ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        "Pop1", ...
        "A", ...
        "A*01:01", ...
        0.5, ...
        NaN, ...
        100, ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    metricsMultiplicity = Mobi_reference_population_metrics( ...
        selectedPeptides, combinedTable, referenceTable, struct('hitCountMode', 'multiplicity'));
    metricsBinary = Mobi_reference_population_metrics( ...
        selectedPeptides, combinedTable, referenceTable, struct('hitCountMode', 'binary_per_allele'));

    verifyGreaterThan(testCase, metricsMultiplicity.expectedHits, metricsBinary.expectedHits);
    verifyEqual(testCase, metricsBinary.expectedHits, 0.75, 'AbsTol', 1e-10);
    verifyEqual(testCase, metricsMultiplicity.expectedHits, 1.5, 'AbsTol', 1e-10);
end


function testEqualPopulationWeightMode(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop2"], ...
        ["A"; "A"], ...
        ["A*01:01"; "A*01:01"], ...
        [0.5; 0.1], ...
        [NaN; NaN], ...
        [100; 300], ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    metrics = Mobi_reference_population_metrics( ...
        selectedPeptides, combinedTable, referenceTable, struct('populationWeightMode', 'equal'));

    expectedCoverage = 100 * mean([0.75; 0.19]);
    verifyEqual(testCase, metrics.coveragePercent, expectedCoverage, 'AbsTol', 1e-10);
    verifyEqual(testCase, metrics.populationWeightMode, "equal");
end


function testInvalidFrequencyInputsError(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        "Pop1", ...
        "A", ...
        "A*01:01", ...
        250, ...
        NaN, ...
        100, ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    verifyError(testCase, ...
        @() Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable), ...
        'Mobi:ReferenceMetrics:InvalidAlleleFrequency');
end


function testWarningBehavior(testCase)
    selectedPeptides = "PEP1";

    combinedTable = table( ...
        "PEP1", ...
        "A*01:01", ...
        'VariableNames', {'Peptide','MHC'});

    referenceTable = table( ...
        ["Pop1"; "Pop1"], ...
        ["A"; "A"], ...
        ["A*01:01"; "A*02:01"], ...
        [0.8; 0.7], ...
        [NaN; NaN], ...
        [0; 0], ...
        'VariableNames', {'Population','Locus','Allele','AlleleFrequency','IndividualsFrequency','SampleSize'});

    f = @() Mobi_reference_population_metrics(selectedPeptides, combinedTable, referenceTable);
    verifyWarning(testCase, f, 'Mobi:ReferenceMetrics:NonpositiveSampleSize');
end
